### PR TITLE
allow to customize transform callback in client configuration

### PR DESCRIPTION
**Pull request by filipgolonka**
@ftrrtf

### CODE REVIEW

**Comment by ftrrtf** [comment]
@filipgolonka thanks for MR, could you check why CI is broken?

**Comment by filipgolonka** [comment]
timeouts during `composer install` on PHP5.5 and 5.6 on Symfony 2.8. Can you restart build on travis?

**Comment by filipgolonka** [comment]
pushing empty commit to trigger build

**Comment by ftrrtf** [comment]
@filipgolonka try `travis_wait 20 ***` https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

**Comment by filipgolonka** [comment]
it's green! :)

**Comment by ftrrtf** [comment]
Cool, could you please clean up commits and I'll release a new version this evening.

**Comment by filipgolonka** [comment]
done :) thanks!

**Pull request merged**
