### PR TITLE
Upgrade js-notifier to v1.5

### PR DESCRIPTION
**Pull request by filipgolonka**
@mplachta @ftrrtf

### CODE REVIEW

**Comment by ftrrtf** [comment]
:+1:

**Comment by ftrrtf** [comment]
@mplachta ping

**Comment by mplachta** [comment]
yeap, good sorry, maybe such small changes as this doesn't require two :+1: ? it's so simple :)

**Comment by filipgolonka** [comment]
@ftrrtf or @mplachta can you merge it and release a new version?

**Comment by mplachta** [comment]
yeap

**Pull request merged**
