### PR TITLE
Update scrutinizer config

### PR DESCRIPTION
**Pull request by ftrrtf**

### CODE REVIEW

**Comment by ftrrtf** [comment]
@mplachta please have a look on it

**Comment by mplachta** [comment]
Looks good, generally I think that following PSR-2 is crucial here.

I think that scrutinizer is good, but maybe we should add phpmd and phpcs as dependencies so the developer is able to perform quality check on his own?

Take a look at https://github.com/Schibsted-Tech-Polska/php-sndapi (especially composer.json and gruntfile.js).

Also remember to squash commits before you merge, it's easier to find all changes in the future.

**Comment by ftrrtf** [comment]
@mplachta I would not like to add a new dependencies (node/npm/grunt) for this, especially it's not PHP stack.

**Comment by mplachta** [comment]
Sure, that just makes it easier to run all tools.
What about adding phpmd, phpcs, phpcpd and phploc? This way anybody contributing could check the code before sending pull-request.

**Comment by ftrrtf** [comment]
@mplachta Yes, I think it makes sense to add it. But certainly not in this brunch.

**Comment by mplachta** [comment]
Cool, go ahead then :) :+1:

**Pull request merged**
