### PR TITLE
delivered spec tests for bundle

### PR DESCRIPTION
**Pull request by ralfmaxxx**
Hi! I delivered some missing phpspec tests for this package.

**DONE**
* more phpspec tests
* update `README.md` with minimum PHP version requirement
* I corrected inherit phpdoc tag (https://www.phpdoc.org/docs/latest/guides/inheritance.html#the-inheritdoc-tag)

### CODE REVIEW

**Comment by filipgolonka** [comment]
:+1:

**Comment by bartosz-kahl** [comment]
👍

**Comment by ghostal** [comment]
Not sure whether this package still intends to support it (`README.md` seems to suggest so), but using `::class` will break b/c with Symfony 2.x, as minimum requirements for 2.x are PHP 5.3.9, while magic class name constants weren't introduced until PHP 5.5.

**Comment by filipgolonka** [comment]
@ghostal check composer.json - now php is required in `>=5.5.9` version. @ralfmaxxx can you fix README.md?

**Comment by ralfmaxxx** [comment]
@filipgolonka yes i can. @ghostal i was following requirements from `composer.json`

**Comment by ghostal** [comment]
@ralfmaxxx @filipgolonka Ahh yes, I see it. Carry on! :sweat_smile: :+1:

**Comment by ralfmaxxx** [comment]
Ok, now it's ready!

**Pull request merged**
